import React, { Component } from 'react';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import { changeValue, setSignUpData } from 'actions/login';
import Banner from 'components/wana-ui/banner';
import Icon from 'components/wana-ui/icon';
import NavMenu from 'components/global/navmenu';
import Footer from 'components/global/footer';
import SignUp from 'components/forms/SignUp';
import cookie from 'react-cookies';

@connect(state => ({

}))

class Terms extends Component {

  constructor(props) {
    super(props);
  }

  setSignUpData = (signUpData) => {
    console.log("DATA: ", signUpData)
    const { dispatch, history } = this.props;
    dispatch(setSignUpData(signUpData));
    history.push('/signup_complete');

  }
  render() {
    const { props } = this;
    return (
      <div>
        <NavMenu
          history={this.props.history}
        />

        <section className="section -bg-white cf">
          <div className="container body">

            <h1 className="heading">Wana Terms of Use Agreement</h1>
            <hr className="hairline"/>
            <p>PLEASE READ THE FOLLOWING TERMS OF USE AGREEMENT CAREFULLY. BY ACCESSING OR USING OUR SITES AND OUR SERVICES, YOU HEREBY AGREE TO BE BOUND BY THE TERMS AND ALL TERMS INCORPORATED HEREIN BY REFERENCE. IT IS THE RESPONSIBILITY OF YOU, THE USER, MEMBER, OR PROSPECTIVE MEMBER TO READ THE TERMS AND CONDITIONS BEFORE PROCEEDING TO USE THIS SITE. IF YOU DO NOT EXPRESSLY AGREE TO ALL OF THE TERMS AND CONDITIONS, THEN PLEASE DO NOT ACCESS OR USE OUR SITES OR OUR SERVICES. THIS TERMS OF USE AGREEMENT IS EFFECTIVE AS OF 10/20/2017.</p>
            <h3>ACCEPTANCE OF TERMS</h3>
            <p>The following Terms of Use Agreement (the &ldquo;Terms&rdquo;) is a legally binding agreement that shall govern the relationship with our users and others which may interact or interface with Wana Family Network LLC, also known as Wana, located at 3371 Glendale Blvd. #142, Los Angeles, California 90039, and our subsidiaries and affiliates, in association with the use of the Wana website, which includes <a href="http://wanafam.ly">http://wanafam.ly</a> and any other websites, pages, or mobile applications operated by Wana, (the "Site") and its Services, which shall be defined below. </p>
            <p>These Terms are subject to change by Wana without notice, from time to time, at our sole discretion. &nbsp;Changes to these Terms will be posted to the Site at <a href="http://wanafam.ly/terms">http://wanafam.ly/terms</a>. &nbsp;Your continued use of the Site and/or Services constitute acceptance of any and all changes.</p>
            <h3>PRIVACY POLICY</h3>
            <p>Every User&rsquo;s registration data and various other personal information are strictly protected by the Wana Family Network LLC Privacy Policy (see the full Privacy Policy at http://wanafam.ly/privacy). As a User, you herein consent to the collection and use of the information provided, including the transfer of information within the United States and/or other countries for storage, processing or use by Wana Family Network LLC and/or our subsidiaries and affiliates. </p>
            <h3>DESCRIPTION OF SERVICES OFFERED</h3>
            <p>Wana Family Network LLC offers Services, both online and offline, to help families with children meet other families with children for the purpose of exchanging babysitting services. &nbsp;</p>
            <p>Any and all visitors to our Site, whether they are registered or not, shall be deemed as "Users" for the purpose of these Terms. Once an individual registers for our Services, through the process of creating an account, the User shall then be considered a "Member." &nbsp;Either a Member or User who represents a household of adults with child dependents shall be considered a &ldquo;Family.&rdquo;</p>
            <p>Our Services include but are not limited to:</p>
            <ul className="list list--bulleted">
              <li>We enable Families to post profiles on the Site for the purpose of requesting and/or offering babysitting services to other Families.</li>
              <li>We provide a scheduler to help Families organize babysitting with other Families.</li>
              <li>We enable Families to acquire, give, and receive virtual points (&ldquo;Points&rdquo;) on the Site for the purpose of trading babysitting services equitably, and to monitor their inventory and usage of Points. </li>
              <li>We enable Families to self-identify as having an affiliation with certain schools and local groups for the purpose of describing their Family and for identifying other Families of similar interests.</li>
              <li>We provide search functionality (&ldquo;Search Services&rdquo;) on the Site to allow Families to identify other Families they are interested in meeting based on their needs, preferences, and affiliations, and we provide a messaging platform that allows Families to communicate without sharing contact information.</li>
              <li>We provide tools to help Families make more informed decisions, such as (i) our safety guide at http://wanafam.ly/safety, (ii) trust indicators on Family profiles, which show other Families&rsquo; quantity of activity on the Site, and (iii) peer reviews on Family profiles, which show other Families&rsquo; quality of activity on the Site.</li>
              <li>We provide notification of events outside the Site that Families may choose to attend.</li>
            </ul>
            <p>The user and/or member acknowledges and agrees that the Services provided and made available through our website and applications, which may include some mobile applications and that those applications may be made available on various social media networking sites and numerous other platforms and downloadable programs, are the sole property of Wana Family Network LLC. At its discretion, Wana Family Network LLC may offer additional website Services and/or products, or update, modify or revise any current content and Services, and this Agreement shall apply to any and all additional Services and/or products and any and all updated, modified or revised Services unless otherwise stipulated. Wana Family Network LLC does hereby reserve the right to cancel and cease offering any of the aforementioned Services and/or products. You, as the end user and/or member, acknowledge, accept and agree that Wana Family Network LLC shall not be held liable for any such updates, modifications, revisions, suspensions or discontinuance of any of our Services and/or products. </p>
            <p>Furthermore, the user and/or member understands, acknowledges and agrees that the Services offered shall be provided "AS IS" and as such Wana Family Network LLC shall not assume any responsibility or obligation for the timeliness, missed delivery, deletion and/or any failure to store user content, communication or personalization settings. </p>
            <h3>LIMITATION OF SERVICES</h3>
            <p>Wana does not employ any family, individual, or entity for the purpose of providing babysitting. Members are responsible for compliance with any and all applicable laws in connection with relationships they establish with other Members. Wana does not have and expressly disclaims control over the quality, timing, suitability, or legality of the services provided by Members, or the integrity, responsibility, or actions of Members, whether through public, private, or offline interactions. </p>
            <p>Wana accepts Membership of Users through account registration. In providing this Service, we are not referring or endorsing any Member, nor making any claim of the quality, reliability, suitability, or responsibility of the Member, nor the quality, integrity, or accuracy of information provided by the Member.</p>
            <p>Through the Search Services on the Site, we may offer Users a customized list of Families to consider for babysitting based on information, including needs, preferences, and affiliations, provided to us by the User. In providing these Services, we are not referring or endorsing any Family. We are also not providing any medical, diagnostic, treatment, or clinical service nor engaging in any conduct that requires a professional license.</p>
            <p>Members may select certain school or local group affiliations to show as part of their profile. Unless expressly stated otherwise, Wana is not affiliated with and does not refer or recommend any of these organizations, nor do we verify the Member&rsquo;s affiliation with these organizations.</p>
            <p>Most Member content is user generated, and we do not control, review, or verify the accuracy of user generated content. Wana expressly disclaims responsibility for the quality, accuracy, or reliability of information provided by Members on or off the Site. We may offer Members the opportunity to verify certain information such as address, email address, or phone number. If we indicate that a Member has verified this information, it means that they have complied with a process established and provided by us or a third party to assess the accuracy of the information. Wana makes no claim or guarantee of the actual accuracy of the information provided to us or a third party for this process, nor does Wana make claim to the thoroughness, completeness, timeliness, accuracy, or quality of the verification process. </p>
            <p><strong>Any screening conducted by Wana of a Member or information provided by that Member is limited and should not be taken as complete, accurate, up-to-date, or conclusive of the Member&rsquo;s suitability to provide babysitting. &nbsp;Users are solely responsible for screening, interviewing, performing background checks on, collecting reference checks on, verifying information provided by, and selecting appropriate Members to provide babysitting services. &nbsp;Please visit </strong><a href="http://www.wannawana.com/safety"><strong>http://wanafam.ly/safety</strong></a><strong> for additional guidance on making informed safety decisions. &nbsp;Each Family is responsible for complying with all applicable laws in connection with any relationship they establish.</strong></p>
            <p><strong>Wana is not responsible for the conduct, whether online or offline, of any Family, Member, or User of the Site or Services. &nbsp;Moreover, Wana does not assume and expressly disclaims any liability that may result from the use of information provided on our Site. &nbsp;All Families, Members, and Users hereby expressly agree not to hold Wana (or Wana&rsquo;s members, managers, employees, subsidiaries, successors, assignees, agents, representatives, private contractors, advertisers, marketing partners, licensors, resellers, or other affiliates, hereinafter &ldquo;Affiliates&rdquo;) liable for the actions or inactions of any Family, Member, User, or other third party or for any information, instruction, advice, or services which originated through the Site, and, Wana and its Affiliates expressly disclaims any liability whatsoever for any damage, suits, claims, and/or controversies that have arisen or may arise, whether known or unknown therefrom.&nbsp;</strong></p>
            <h3>ELIGIBILITY</h3>
            <p>By requesting to use, registering to use, and/or using the Site or the Services, you represent and warrant that you have the right, authority, and capacity to enter into these Terms and you commit to abide by all of the terms and conditions hereof. &nbsp;You are responsible for providing accurate, current, and complete information in connection with your registration, and you will register your account in your own legal name.</p>
            <p>You also represent and warrant that you meet the following eligibility criteria:</p>
            <ul className="list list--bulleted">
              <li>Our Services are available only to individuals who are eighteen (18) years of age or older and who have child dependents seventeen (17) years of age or younger. Wana will not knowingly collect any information from individuals under 18, nor will Wana accept individuals as Members who do not have children under 18. If you do not meet the above age and/or family composition requirements, do not register to use the Site or Services. Should we determine that you do not meet the age and/or family composition requirements for using our Site or Services, your registration will be terminated immediately.</li>
              <li>The Site and Services are currently available only to individuals residing in the United States or Puerto Rico.</li>
              <li>Neither you nor any member of your household may have ever been (i) the subject of a complaint, restraining order, or any other legal action involving, arrested for, charged with, or convicted of a felony, any criminal offense involving violence, abuse, neglect, fraud, or larceny, or any offense that involves endangering the safety of others, dishonesty, negligence, or drugs, or (ii) registered, or currently required to register, as a sex offender with any government entity.</li>
              <li>You must not be a competitor of Wana or using our Services for reasons that are in competition with Wana.</li>
            </ul>
            <p>If anyone knowingly provides any information of a false, untrue, inaccurate or incomplete nature, Wana Family Network LLC will have sufficient grounds and rights to suspend or terminate the Member in violation of this aspect of the Terms, and as such refuse any and all current or future use of Wana Family Network LLC Services, or any portion thereof. </p>
            <h3>EXCLUSIVE USE AND SECURITY</h3>
            <p>When you set up an account, you are the sole authorized user of your account, even if you are representing multiple adults in your household. &nbsp;When seeking babysitting services, you may use your account only to arrange care for your children, your grandchildren, or individuals for whom you are the legal guardian. &nbsp;When offering babysitting services, you may use your account only to arrange care provided by yourself in your own home. &nbsp;You may from time to time arrange for babysitting services to be provided by another adult represented as a member of your household in your Member account only as agreed upon and acknowledged in writing by the Member receiving those services. </p>
            <p>You are responsible for all activity on and use of your account, and you may not assign or otherwise transfer your account to any other person or entity. &nbsp;You shall be responsible for maintaining the secrecy and confidentiality of your password and for all activities that transpire on or within your account. It is your responsibility for any act or omission of any user(s) that access your account information that, if undertaken by you, would be deemed a violation of the Terms. It shall be your responsibility to notify Wana immediately (<a href="about:blank">help@wanafam.ly)</a> if you notice any unauthorized access or use of your account or password or any other breach of security. Wana Family Network LLC shall not be held liable for any loss and/or damage arising from any failure to comply with this term and/or condition of the Terms.</p>
            <h3>CONDUCT</h3>
            <p>The following rules pertain to &ldquo;Content,&rdquo; and defined as any communications, images, sounds, videos, and all the material, data, and information that you upload or transmit through the Site or Services, or that other users upload or transmit, including without limitation any content, messages, photos, audios, videos, reviews, or profiles that you publish or display (hereinafter, &ldquo;post&rdquo;). &nbsp;By posting any Content while using our Service, you agree, represent, and warrant as follows:</p>
            <ul className="list list--bulleted">
              <li>You will not post any photographs, names, or personal identifying information about any minors for whom you are not the parent or legal guardian. </li>
              <li>You are solely responsible for any Content that you post on the Site, or transmit to other Users of the Site. &nbsp;You will not post on the Site, or transmit to other users, any defamatory, inaccurate, abusive, obscene, profane, offensive, sexually oriented, threatening, harassing, defamatory, racially offensive, or illegal material, or any material that infringes or violates another party&rsquo;s rights (including, but not limited to, intellectual property rights, and rights of privacy and publicity), or advocate, promote, or assist, in any unlawful act such as (by way of example only) copyright infringement or computer misuse, or give the impression that any Content emanates from Wana where this is not the case. &nbsp;You will not provide inaccurate, misleading, defamatory, or false information to Wana or to any other User of the Site, and all opinions stated as part of Content must be genuinely held.</li>
              <li>You understand and agree that Wana may, in its sole discretion, review, edit, and delete any Content, in each case in whole or in part, that in the sole judgment of Wana violates these Terms or which Wana determines in its sole discretion might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of users of the Site or others.</li>
              <li>You have the right, and hereby grant, to Wana, its Affiliates, licensees and successors, an irrevocable, perpetual, non-exclusive, fully paid-up, transferable, worldwide license to use, copy, perform, display, reproduce, adapt, modify, and distribute your Content and to prepare derivative works of, or incorporate into other works, such Content, and to grant and authorize sublicenses of the foregoing. &nbsp;You further represent and warrant that public posting and use of your Content by Wana will not infringe or violate the rights of any third party.</li>
              <li>You may receive the personal information of other Users. &nbsp;Any personal information you receive may only be used for the specific purpose it was provided to you. &nbsp;You may not directly or indirectly disclose or sell the information to any other person or entity, and Users may not contact other Users for any purpose other than coordinating babysitting using the Wana platform. &nbsp;</li>
              <li>You agree that Wana has no obligation to remove any reviews or other information posted on the Site about you or any other person or entity. &nbsp;You may not terminate your registration and re-register in order to prevent a review from being associated with your account. &nbsp;The author of a review can always remove or request removal of a review they have written.</li>
              <li>You may not use the Site or Services, or information obtained from the Site or Services, for the purpose of circumventing the Site&rsquo;s messaging or scheduling tools, including for the purpose of avoiding the obligation to pay fees to Wana.</li>
              <li>Your use of the Services, including but not limited to the Content you post on the Site, must be in accordance with any and all applicable laws and regulations.</li>
              <li>Wana is not responsible for any claims relating to any inaccurate, untimely, or incomplete information provided by Users of the Site.</li>
              <li>You agree that any comments, ideas, messages, questions, suggestions, or other communications you provide to us through any channel (including, without limitation, the Site, email, telephone, surveys, and our social media accounts) shall be and remain the exclusive property of Wana and we may use all such communications, all without notice to, consent from, or compensation to you.</li>
            </ul>
            <p>Opinions, advice, statements, offers, or other information or content made available on the Site or through the Site, but not directly by Wana, are those of their respective authors. &nbsp;Such authors are solely responsible for such content. &nbsp;Wana does not: (i) guarantee the accuracy, completeness, or usefulness of any information on the Site or available through the Service, or (ii) adopt, endorse, or accept responsibility for the accuracy or reliability of any opinion, advice, or statement made by any party that appears on the Site or through the Service. &nbsp;Under no circumstances will Wana or its Affiliates be responsible for any loss or damage resulting from: (a) your reliance on information or other content posted on the Site or transmitted to or by any user of the Site or Services; or (b) reviews or comments made about you on the Site by other users.</p>
            <p><strong>Wana disclaims any liability whatsoever for any misstatements and/or misrepresentations made by any users of the Site. &nbsp;Users hereby represent, understand, and agree to hold Wana harmless for any mistreatments and/or misrepresentations made by or on behalf of them on this Site or in any other venue.</strong></p>
            <p>Furthermore, you herein agree that you will not under any circumstance:</p>
            <ul className="list list--bulleted">
              <li>provide false or inaccurate information when registering for an account, communicating with Wana and/or other Users, or otherwise using the Site and/or Services;</li>
              <li>post any content that shall be deemed unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or invasive of another's privacy or which is hateful, and/or racially, ethnically, sexually, religiously, or otherwise objectionable;</li>
              <li>impersonate any individual or entity, including, but not limited to, any Member, Wana official, or Wana affiliate, or falsely stating or otherwise misrepresenting any affiliation with an individual or entity;</li>
              <li>post any such content that may infringe upon any patent, copyright, trademark, or any other proprietary or intellectual rights of any other party;</li>
              <li>post any content that you do not personally have any right to offer pursuant to any law or in accordance with any contractual or fiduciary relationship;</li>
              <li>post any unsolicited or unauthorized advertising, promotional flyers, "junk mail," "spam," or any other form of solicitation;</li>
              <li>post any source that may contain a software virus or other computer code, any files and/or programs which have been designed to interfere, destroy and/or limit the operation of any computer software, hardware, or telecommunication equipment;</li>
              <li>disrupt the normal flow of communication, or otherwise act in any manner that would negatively affect other users' ability to participate in any real time interactions;</li>
              <li>interfere with or disrupt any Services, servers and/or networks that may be connected or related to our Site, including, but not limited to, the use of any device software and/or routine to bypass the robot exclusion headers;</li>
              <li>"stalk" or act with the intent to otherwise harass another individual; and/or </li>
              <li>collect or store any personal data relating to any other Member or User in connection with the aforementioned prohibited conduct and/or activities.</li>
            </ul>
            <p>Wana Family Network LLC herein reserves the right to pre-screen, refuse and/or delete any content currently available through our Services. In addition, we reserve the right to remove and/or delete any such content that would violate the Terms or which would otherwise be considered offensive to other visitors, users and/or members. </p>
            <p>Wana Family Network LLC herein reserves the right to access, preserve and/or disclose member account information and/or content if it is requested to do so by law or in good faith belief that any such action is deemed reasonably necessary for:</p>
            <ul className="list list--bulleted">
              <li>compliance with any legal process;</li>
              <li>enforcement of the Terms;</li>
              <li>responding to any claim that therein contained content is in violation of the rights of any third party;</li>
              <li>responding to requests for customer service; or</li>
              <li>protecting the rights, property or the personal safety of Wana Family Network LLC, its visitors, users and members, including the general public.</li>
            </ul>
            <p><strong>As a user or member of the Site, you herein acknowledge, understand and agree that all information, text, software, data, photographs, music, video, messages, tags or any other content, whether it is publicly or privately posted and/or transmitted, is the expressed sole responsibility of the individual from whom the content originated. You are solely responsible for any and all content posted, uploaded, emailed, transmitted or otherwise made available by way of the Wana Services, and as such, we do not guarantee the accuracy, integrity or quality of such content. It is expressly understood that by use of our Services, you may be exposed to content including, but not limited to, errors, omissions, or falsehoods in the content posted, or content that is obscene, unlawful, offensive, or otherwise harmful. &nbsp;Wana expressly disclaims any responsibility for this content and/or any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted or otherwise made available by Wana. </strong></p>
            <h3>TERMINATION</h3>
            <p>Wana reserves the right in its sole discretion to terminate your access to all or part of the Wana Site and/or Services, to remove your profile and/or any content posted by or about you from the Site, and/or to terminate your account with Wana, with or without notice for any reason or no reason in its sole discretion. If we terminate your registration, we have no obligation to notify you of the reason, if any, for your termination.</p>
            <p>The cause for such termination, discontinuance, suspension and/or limitation of access may include, but is not limited to:</p>
            <ul className="list list--bulleted">
              <li>any breach or violation of our Terms or any other incorporated agreement, regulation and/or guideline;</li>
              <li>by way of requests from law enforcement or any other governmental agencies;</li>
              <li>the discontinuance, alteration and/or material modification to our Services, or any part thereof;</li>
              <li>unexpected technical or security issues and/or problems;</li>
              <li>any extended periods of inactivity;</li>
              <li>any engagement by you in any fraudulent or illegal activities; and/or</li>
              <li>the nonpayment of any associated fees that may be owed by you in connection with your <a href="http://wanafam.ly">http://wanafam.ly</a> account Services.</li>
            </ul>
            <p>A Family who no longer has children under 18 years of age is no longer eligible to use the Site and/or Services. If you have an existing account but no longer meet the age eligibility requirements, you will no longer have access to the portions of the Site and Services that require account registration. &nbsp;Your profile will no longer be displayed, but other Content you have posted or transmitted (e.g., reviews, messages to other users) may or may not (in our sole discretion) remain on the Site. &nbsp;For assistance reactivating your account, contact help@wanafam.ly. </p>
            <p>You may terminate your own account at any time. &nbsp;You may re-register at any time, but your previous information and activity, including any Content you may have created and any Points associated with your account, may no longer be available. &nbsp;Any Promotion Points offered to new users are only available once per household; you will not receive any Promotion Points intended for new users upon re-registration.</p>
            <p>Upon termination of your account, you will no longer have access to the portions of the Site and Services that require account registration. &nbsp;If your account is terminated, your profile will no longer be displayed, but other Content you have posted or transmitted (e.g., reviews, messages to other users) may or may not (in our sole discretion) remain on the Site. &nbsp;Any Content associated with your account after your account&rsquo;s termination may not be available to you if you re-register with Wana. &nbsp;Wana shall be under no obligation to provide you with a copy of any content posted by or about you on the Site. &nbsp;</p>
            <p><strong>Following any termination of any individual&rsquo;s use of the Site or the Services, Wana reserves the right to send a notice thereof to other Users with whom we believe the individual has corresponded.</strong> &nbsp;Our decision to terminate an individual&rsquo;s registration and/or to notify other Members with whom we believe the individual has corresponded does not constitute, and should not be interpreted or used as information bearing on, the individual&rsquo;s character or general reputation.</p>
            <h3>PAYMENTS AND REFUNDS</h3>
            <p>In order to utilize some Wana Services or product offerings, the user of such Services or product offerings must pay Wana a recurring, one-time, or other fee. &nbsp;In addition, the user is responsible for any state or local taxes associated with the Services or product offerings purchased.</p>
            <p>To the extent you elect to purchase Services or product offerings we offer for a fee, you authorize Wana, or a third party payment processor that works on our behalf, to charge your chosen payment method for the Services and/or products you purchase. You agree that Wana or the designated third party processor may store your payment information in accordance with the appropriate Privacy Policy. &nbsp;We may then charge that payment method for additional Services/products that you purchase, including those that occur automatically as a result of a purchase pre-authorized by you. &nbsp;</p>
            <p>Wana reserves the right to correct any errors or mistakes that it makes even if it has already requested or received payment.</p>
            <p><strong>Except as set forth in these Terms or as described on the Site at the time you make a purchase, all payments for services/products are non-refundable and there are no refund or credits for unused or partially used services/products or service/product cancellations.</strong> &nbsp;Wana does not provide refunds or credits under any circumstances, unless it determines in its sole discretion that a refund or credit is warranted due to extenuating circumstances.</p>
            <p>From time to time, Wana may offer special promotions, points, awards, or discounts (&ldquo;Promotions&rdquo;). All Promotions will be run at the sole discretion of Wana and can be modified or terminated at any time by Wana with or without advance notice. &nbsp;Promotions may be offered on a limited time basis and may be subject to certain additional terms.</p>
            <p>Some Promotions may be offered to first-time users only. &nbsp;Users are eligible to receive the Promotion only if they have never before been a Member. &nbsp;Wana will use information provided by the user to determine eligibility, including but not limited to, name, address, and email address. &nbsp;Determination of eligibility is at the sole discretion of Wana.</p>
            <h3>POINTS </h3>
            <p>You may receive or purchase Points to be used as payment to other Families in exchange for babysitting services, or for other goods and services as described on the Site. &nbsp;</p>
            <p>When a Family requests or offers a sit from or to another Family, Wana provides a suggested number of Points to be transferred upon completion of the sit, based on, but not limited to, the duration of the sit. &nbsp;Both Families are responsible for reviewing and agreeing on the number of Points to transfer prior to booking the sit. Booking is considered confirmation and approval of the recommended Points transfer, unless otherwise specified in writing by the Families. &nbsp;Points will not be transferred until the sit is complete.</p>
            <p>Upon conclusion of the sit, either Family may adjust the parameters of the sit affecting points calculation, including, but not limited to, duration of the sit, based on the final circumstances of the sit; Wana will provide an updated suggested number of Points to be transferred. &nbsp;Either Family may adjust the number of Points to be transferred. When both Families agree on the number of Points to be transferred, the sit is marked as complete, and Points are transferred from the Family who received the sit to the Family who hosted the sit.</p>
            <p>Once a sit is complete and Points are transferred, the transfer is final. Wana is not responsible for any error or dissatisfaction in the transfer of Points arising from the actions of the users.</p>
            <p>All sits will auto-complete after three (3) days from the conclusion of the sit if not already approved for completion by the Families. At that time, the number of Points agreed upon when the sit was booked will be transferred. The transfer is final. Wana will not be held responsible for the satisfaction of either Family in the number of Points transferred or the timing of that transfer.</p>
            <p>In the case that Families do not agree on the number of Points to be transferred following a sit, either Family may contact Wana for mediation at help@wanafam.ly. Wana may provide mediation at its sole discretion and is not responsible for the satisfaction of either Family in the resolution of the disagreement. Any decision by Wana is final.</p>
            <p>If an agreement is not reached within 3 days of the conclusion of the sit, whether or not Wana has participated in mediation, the sit will auto-complete, and the number of Points agreed upon when the sit was booked with be transferred. The transfer is final.</p>
            <p>Points have no monetary or cash value, and your receipt or purchase of Points does not represent a pre-funding of stored cash value that can be accessed or used in the future for any purpose. &nbsp;Points cannot be sold, transferred, or exchanged for &ldquo;real world&rdquo; money or cash. &nbsp;Points may only be transferred or purchased in whole numbers. Points do not expire. </p>
            <p>If you purchase Points, you agree to pay Wana the price indicated on the Site at the time you make your purchase. &nbsp;You agree that all sales of Points are final and non-refundable and you are not entitled to a refund of any unused Points, including in the event that you close your account or your registration is terminated by us. </p>
            <h3>LINKS TO EXTERNAL SITES, ADVERTISERS, AND THIRD PARTIES</h3>
            <p>Links to external sites or inclusion of advertisements or other third-party content on Wana do not constitute an endorsement by Wana of any such third-party individual, entity, site, advertisement, content, product, or other materials presented by the third party. Wana is not responsible for any content presented by a third party.</p>
            <p>User further acknowledges that use of any site or content controlled, owned, or operated by a third party is not subject to Wana&rsquo;s Terms of Use or Privacy Policy. &nbsp;You herein agree that Wana shall not be held responsible or liable for any loss or damage of any nature or manner that may result from the use of links that may appear throughout the Site or Services.</p>
            <h3>LINKS</h3>
            <p>Either Wana Family Network LLC or any third parties may provide links to other websites and/or resources. Thus, you acknowledge and agree that we are not responsible for the availability of any such external sites or resources, and as such, we do not endorse nor are we responsible or liable for any content, products, advertising or any other materials, on or available from such third party sites or resources. Furthermore, you acknowledge and agree that Wana Family Network LLC shall not be responsible or liable, directly or indirectly, for any such damage or loss which may be a result of, caused or allegedly to be caused by or in connection with the use of or the reliance on any such content, goods or Services made available on or through any such site or resource.</p>
            <h3>INTERNAL BACKGROUND CHECKS</h3>
            <p>By registering for and using the Site and/or Services, you hereby acknowledge and agree that Wana has the right, but not the obligation, to use a third-party consumer reporting agency on an ongoing basis to use your personal information to run periodic background checks on you for the legitimate business purpose of protecting the safety and integrity of the Site and its Users (&ldquo;Internal Background Checks&rdquo;). &nbsp;Wana may order these checks when you register with the Site and thereafter in connection with your continued use of our Services and/or interaction with our Site (such as by contacting or communicating with other Users, requesting or offering a sit, etc.).</p>
            <p>The Internal Background Checks are regulated by the Fair Credit Report Act (&ldquo;FCRA&rdquo;), and the background reports resulting form these services are considered &ldquo;consumer reports&rdquo; under FCRA. &nbsp;Consumer reports may contain information on your character, general reputation, personal characteristics, and mode of living, including but not limited to consumer credit, criminal history, worker&rsquo;s compensation, driving, employment, military, civil, and educational data and reports. &nbsp;</p>
            <p>You understand and agree that Wana may review the information provided by the third-party consumer reporting agency and that Wana retains the right to terminate your Wana registration based on the information it receives from these checks, even if such information was subsequently dismissed. </p>
            <p>BY AGREEING TO THESE TERMS AND USING OUR SITE AND SERVICES, YOU AGREE TO ALLOW WANA TO PERFORM THESE INTERNAL BACKGROUND CHECKS FOR THE PURPOSES DESCRIBED ABOVE. &nbsp;IF YOU DO NOT WANT THESE INTERNAL BACKGROUND CHECKS TO BE PERFORMED, YOU SHOULD NOT USE WANA. &nbsp;NO FURTHER CONSENT FROM YOU IS REQUIRED FOR THESE CHECKS TO BE PERFORMED. </p>
            <p>You further expressly acknowledge that Wana has no obligation to perform Internal Background Checks on any Users. To the extent Wana performs such checks on certain Users, the checks are limited and should not be taken as complete, accurate, up-to-date, or conclusive evidence of the accuracy of any information those Users have provided or of their eligibility to use the Site and the Service. &nbsp;Moreover, you hereby represent, understand, and expressly agree that those checks are completed by a third-party consumer reporting agency (not Wana), that the specific records searched and the comprehensiveness of the search varies by the type of background check ordered as well as the state and county where the check is performed, and that the checks are not always accurate or a complete compilation of a person&rsquo;s criminal history.</p>
            <p>California Business and Professions Code Section 18890.2 requires our Site to include the following statement:</p>
            <p>&ldquo;Trustline is California&rsquo;s official background check for license-exempt babysitting providers (i.e. babysitters and nannies) and the only authorized screening program in California with access to fingerprint records at the California Department of Justice and the Federal Bureau of Investigation and access to the California Child Abuse Central Index. The Trustline registry toll-free number is 1 (800) 822-8490.&rdquo;</p>
            <p>Wana may or may not use Trustline as a third-party verification service, at its sole discretion.</p>
            <h3>RELEASE OF LIABILITY FOR CONDUCT</h3>
            <p>Wana is not an employer of any individual, family, or entity for the purpose of providing babysitting. &nbsp;Families may seek and receive babysitting services from other Families and/or may offer and provide babysitting services to other Families through the use of the Site or Services. &nbsp;</p>
            <p>In some instances, such as through Search Services, we may offer Users a customized list of Families to consider for babysitting based on information, including needs, preferences, and affiliations, provided to us by the User. &nbsp;However, if a user agrees on the provision of services to or from a Family we identify through any of those Services, such agreement is solely between the two Families; Wana is not a party to any such agreement.</p>
            <p>Any issues concerning the conduct of a User including, without limitation, the babysitting services received or provided by a Family, the behavior of Family members before, during, or after a sit, the negotiation of Points transfer in connection with a sit, or any Content posted to the Site by any User, must be resolved directly by the Users involved. &nbsp;Wana will not be held responsible and expressly disclaims any liability whatsoever for any claims, demands, or damages (actual or consequential, direct or indirect) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such issues.</p>
            <p>By using this Site or our Services, you hereby represent, understand, and expressly agree to hold Wana harmless for any claim or controversy that may arise out of the actions of or relationship between you and any User, Member, or Family of the Site. &nbsp;You agree to take reasonable precautions in all interactions with Users of the Site or the Services, both online and offline. &nbsp;In addition, you agree to read <a href="http://www.wannawana.com/safety">http://wanafam.ly/safety</a> prior to using the Service for additional guidance on making informed safety decisions. &nbsp;By using the Site or the Services, you agree to immediately report any alleged improprieties of any Users therein to <a href="mailto:help@wanafam.ly">help@wanafam.ly</a>. &nbsp;</p>
            <h3>INDEMNITY</h3>
            <p>By agreeing to these Terms, users of the Site and Services agree to indemnify, defend, and hold harmless Wana and its Affiliates from and against any and all claims, losses, expenses, or demands of liability, including reasonable legal fees and costs incurred by Wana and its Affiliates in connection with any claim by a third party (including an intellectual property claim) arising out of (i) materials and content you submit, post, or transmit though the Site, (ii) use of the Site or Services by you in violation of these Terms of Use or in violation of any applicable law, or (iii) any relationship of agreement formed with a User using the Site or Services. &nbsp;Users further agree that they will cooperate as reasonably required in the defense of such claims. &nbsp;Wana and its Affiliates reserve the right, at their own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by Users, and Users shall not, in any event, settle any claim or matter without the written consent of Wana. &nbsp;Users further agree to hold harmless Wana and its Affiliates from any claim arising from a third party&rsquo;s use of information or materials of any kind posted to the Site by Users.</p>
            <h3>WARRANTY DISCLAIMERS</h3>
            <p>YOU HEREIN EXPRESSLY ACKNOWLEDGE AND AGREE THAT:</p>
            <ul className="list list--bulleted">
              <li>THE USE OF WANA FAMILY NETWORK LLC SERVICES AND SOFTWARE ARE AT THE SOLE RISK BY YOU. OUR SERVICES AND SOFTWARE SHALL BE PROVIDED ON AN "AS IS" AND/OR "AS AVAILABLE" BASIS. WANA FAMILY NETWORK LLC AND OUR AFFILIATES EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF ANY KIND WHETHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</li>
              <li>WANA FAMILY NETWORK LLC AND OUR AFFILIATES MAKE NO SUCH WARRANTIES THAT (i) THE WANA SITE OR SERVICES WILL MEET YOUR REQUIREMENTS; (ii) THE WANA SITE OR SERVICES SHALL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (iii) THAT SUCH RESULTS WHICH MAY BE OBTAINED FROM THE USE OF THE WANA SITE OR SERVICES WILL BE ACCURATE OR RELIABLE; (iv) QUALITY OF ANY PRODUCTS, SERVICES, ANY INFORMATION OR OTHER MATERIAL WHICH MAY BE PURCHASED OR OBTAINED BY YOU THROUGH THE SITE OR SERVICES WILL MEET YOUR EXPECTATIONS; AND (v) THAT ANY SUCH ERRORS CONTAINED IN THE SITE OR SERVICES SHALL BE CORRECTED.</li>
              <li>ANY INFORMATION OR MATERIAL DOWNLOADED OR OTHERWISE OBTAINED BY WAY OF THE WANA SITE OR SERVICES SHALL BE ACCESSED BY YOUR SOLE DISCRETION AND SOLE RISK, AND AS SUCH YOU SHALL BE SOLELY RESPONSIBLE FOR AND HEREBY WAIVE ANY AND ALL CLAIMS AND CAUSES OF ACTION WITH RESPECT TO ANY DAMAGE TO YOUR COMPUTER AND/OR INTERNET ACCESS, DOWNLOADING AND/OR DISPLAYING, OR FOR ANY LOSS OF DATA THAT COULD RESULT FROM THE DOWNLOAD OF ANY SUCH INFORMATION OR MATERIAL.</li>
              <li>NO ADVICE AND/OR INFORMATION, DESPITE WHETHER WRITTEN OR ORAL, THAT MAY BE OBTAINED BY YOU FROM OUR SITE OR SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS.</li>
            </ul>
            <p>IN ADDITON, AND WITHOUT LIMITING THE FOREGOING, WANA MAKES NO PRESENTATION OR WARRANTIES OF ANY KIND WHETHER EXPRESS OR IMPLIED REGARDING THE SUITABILITY OF ANY USER OF OUR SITE TO PROVIDE OR RECEIVE BABYSITTING SERVICES.</p>
            <h3>ASSUMPTION OF RISK</h3>
            <p>You assume all risk when using the Site and the Services, including but not limited to all of the risks associated with any online or offline interactions with Users of the Site or the Services. &nbsp;You agree to take and be held solely responsible for all necessary precautions when interacting with other Users, including but not limited to reviewing <a href="http://wanafam.ly/safety">http://wanafam.ly/safety</a> for guidance in making informed safety decisions.</p>
            <h3>LIMITATION OF LIABILITY</h3>
            <p>YOU EXPLICITLY ACKNOWLEDGE, UNDERSTAND AND AGREE THAT WANA FAMILY NETWORK LLC AND OUR AFFILIATES SHALL NOT BE LIABLE TO YOU FOR ANY PUNITIVE, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, LOSSES, OR EXPENSES, EVEN THOUGH WE MAY HAVE BEEN ADVISED OF SUCH POSSIBILITY THAT SAID DAMAGES MAY OCCUR, INCLUDING, BUT NOT LIMITED TO, DAMAGES WHICH MAY BE RELATED TO:</p>
            <ul className="list list--bulleted">
              <li>THE USE OR INABILITY TO USE OUR SITE OR SERVICE; </li>
              <li>ANY INFORMATION RECEIVED OR EXCHANGED THROUGH THE SITE OR SERVICES;</li>
              <li>ANY CONTENT REMOVED FROM THE SITE;</li>
              <li>UNAUTHORIZED ACCESS TO OR THE ALTERATION OF YOUR TRANSMISSIONS AND/OR DATA; </li>
              <li>STATEMENTS OR CONDUCT OF ANY SUCH THIRD PARTY ON OUR SERVICE; </li>
              <li>FAILURE OF PERFORMANCE, ERRORS, OMISSION, DEFECT, INTERRUPTION, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, OR LINE OR SYSTEM FAILURE;</li>
              <li>AND ANY OTHER MATTER WHICH MAY BE RELATED TO OUR SERVICE.</li>
            </ul>
            <p>UNDER NO CIRCUMSTANCES WILL WANA&rsquo;S AGGREGATE LIABILITY, IN ANY FORM OF ACTION WHATSOEVER IN CONNECTION WITH THIS AGREEMENT OR THE USE OF THE SERVICES OR THE SITE, EXCEED THE GREATER OF (I) THE AMOUNT PAID, IF ANY, BY YOU TO WANA IN CONNECTION WITH THE SITE IN THE TWELVE (12) MONTHS PRIOR TO THE ACTION GIVING RISE TO THE LIABILITY, OR $100.</p>
            <p>No Liability for non-Wana Actions. &nbsp;IN NO EVENT WILL WANA BE LIABLE FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, AND/OR CONSEQUENTIAL, ARISING OUT OF OR RELATING TO THE CONDUCT OF YOU OR ANYONE ELSE IN CONNECTION WITH THE USE OF THE SITE OR THE SERVICES OR ANY AGREEMENT OR RELATIONSHIP FORMED USING THE SITE OR SERVICES, INCLUDING WITHOUT LIMITATION, BODILY INJURY, EMOTIONAL DISTRESS, AND/OR ANY OTHER DAMAGES RESULTING FROM ANYONE&rsquo;S RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE SITE, OR TRANSMITTED TO OR BY ANY USERS OR ANY OTHER INTERACTIONS WITH OTHER MEMBERS OF THE SITE OR SERVICES, WHETHER ONLINE OR OFFLINE. &nbsp;THIS INCLUDES ANY CLAIMS, LOSSES, OR DAMAGES ARISING FROM THE CONDUCT OF USERS WHO HAVE REGISTERED UNDER FALSE PRETENSES OR WHO ATTEMPT TO DEFRAUD OR HARM YOU.</p>
            <p>In addition to the preceding paragraphs of this section and other provisions of the Terms, any advice that may be posted on the Site is for informational purposes only and is not intended to replace or substitute for any professional financial, medical, legal, or other advice. &nbsp;Wana makes no representations or warranties and expressly disclaims any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Site. &nbsp;If you have specific concerns or a situation arises in which you require professional or medical advice, you should consult with an appropriately trained and qualified specialist.</p>
            <p>&nbsp;</p>
            <h3>EXCLUSION AND LIMITATIONS</h3>
            <p>THERE ARE SOME JURISDICTIONS WHICH DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OF EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. THEREFORE, SOME OF THE ABOVE LIMITATIONS OF SECTIONS WARRANTY DISCLAIMERS AND LIMITATION OF LIABILITY MAY NOT APPLY TO YOU.</p>
            <h3>CLAIMS AND DISPUTES</h3>
            <p>In the event you have a dispute, you agree to release Wana Family Network LLC (and its officers, directors, employees, agents, parent subsidiaries, affiliates, co-branders, partners and any other third parties) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected or unsuspected, disclosed and undisclosed, arising out of or in any way connected to such dispute.</p>
            <p>In using the Site and/or Services, you waive a trial by jury in any action or proceeding between you and Wana arising out of and/or relating to use of the Site and/or Services.</p>
            <p>Furthermore, you waive any right to pursue disputes on a classwide basis. &nbsp;You agree that no claim or dispute arising out of and/or relating to use of the Site and/or Services may be joined with a claim or dispute of any other person or entity, and you may not assert a claim in a representative capacity on behalf of anyone else in any lawsuit or legal proceeding.</p>
            <p>It is at the mutual agreement of both you and Wana Family Network LLC with regard to the Terms that the relationship between the parties shall be governed by the laws of the state of California without regard to its conflict of law provisions and that any and all claims, causes of action and/or disputes, arising out of or relating to the Terms, or the relationship between you and Wana Family Network LLC, shall be filed within the courts having jurisdiction within the County of Los Angeles, California or the U.S. District Court located in said state. You and Wana Family Network LLC agree to submit to the jurisdiction of the courts as previously mentioned, and agree to waive any and all objections to the exercise of jurisdiction over the parties by such courts and to venue in such courts.</p>
            <p>&nbsp;</p>
            <p>You acknowledge, understand and agree that regardless of any statute or law to the contrary, any claim or action arising out of or related to the use of our Services or the Terms must be filed within 1 year(s) after said claim or cause of action arose or shall be forever barred.</p>
            <h3>PROPRIETARY RIGHTS&nbsp;</h3>
            <p>You do hereby acknowledge and agree that Wana Family Network LLC's Services and any essential software that may be used in connection with our Services ("Software") shall contain proprietary and confidential material that is protected by applicable intellectual property rights and other laws. Furthermore, you herein acknowledge and agree that any Content which may be contained in any advertisements or information presented by and through our Services or by advertisers is protected by copyrights, trademarks, patents or other proprietary rights and laws. Therefore, except for that which is expressly permitted by applicable law or as authorized by Wana Family Network LLC or such applicable licensor, you agree not to alter, modify, lease, rent, loan, sell, distribute, transmit, broadcast, publicly perform and/or created any plagiaristic works which are based on Wana Family Network LLC Services (e.g. Content or Software), in whole or part.</p>
            <p>Wana Family Network LLC herein has granted you personal, non-transferable and non-exclusive rights and/or license to make use of the object code or our Software on a single computer, as long as you do not, and shall not, allow any third party to duplicate, alter, modify, create or plagiarize work from, reverse engineer, reverse assemble or otherwise make an attempt to locate or discern any source code, sell, assign, sublicense, grant a security interest in and/or otherwise transfer any such right in the Software. Furthermore, you do herein agree not to alter or change the Software in any manner, nature or form, and as such, not to use any modified versions of the Software, including and without limitation, for the purpose of obtaining unauthorized access to our Services. Lastly, you also agree not to access or attempt to access our Services through any means other than through the interface which is provided by Wana Family Network LLC for use in accessing our Services.</p>
            <h3>TRADEMARK INFORMATION</h3>
            <p>The contents of the Site, including but not limited to names, logos, service marks, and other copyrights and trademarks, are the property of Wana and protected by international copyright and trademark laws. You herein agree not to display and/or use Site content in any manner without the prior express written consent of Wana.</p>
            <h3>COPYRIGHT OR INTELLECTUAL PROPERTY INFRINGEMENT CLAIMS NOTICE</h3>
            <h3>&amp; PROCEDURES</h3>
            <p>Wana Family Network LLC will always respect the intellectual property of others, and we ask that all of our users do the same. With regards to appropriate circumstances and at its sole discretion, Wana Family Network LLC may disable and/or terminate the accounts of any user who violates our Terms and/or infringes the rights of others. If you feel that your work has been duplicated in such a way that would constitute copyright infringement, or if you believe your intellectual property rights have been otherwise violated, you should provide to us the following information:</p>
            <ul className="list list--bulleted">
              <li>The electronic or the physical signature of the individual that is authorized on behalf of the owner of the copyright or other intellectual property interest;</li>
              <li>A description of the copyrighted work or other intellectual property that you believe has been infringed upon;</li>
              <li>A description of the location of the site which you allege has been infringing upon your work;</li>
              <li>Your physical address, telephone number, and email address;</li>
              <li>A statement, in which you state that the alleged and disputed use of your work is not authorized by the copyright owner, its agents or the law;</li>
              <li>And finally, a statement, made under penalty of perjury, that the aforementioned information in your notice is truthful and accurate, and that you are the copyright or intellectual property owner, representative or agent authorized to act on the copyright or intellectual property owner's behalf.</li>
            </ul>
            <p>The Wana Family Network LLC agent for notice of claims of copyright or other intellectual property infringement can be contacted at:</p>
            <p>Wana Family Network LLC<br />
            3371 Glendale Blvd. #142<br />
            Los Angeles, California 90039<br /><br />
            (747) 231-0567<br />
            <a href="mailto:legal@wanafam.ly">legal@wanafam.ly</a></p>
            <h3>ENTIRE AGREEMENT </h3>
            <p>These Terms constitutes the entire agreement between you and Wana Family Network LLC and shall govern the use of our Services, superseding any prior version of these Terms between you and us with respect to Wana Family Network LLC Services. You may also be subject to additional terms and conditions that may apply when you use or purchase certain other Wana Family Network LLC Services, affiliate Services, third-party content or third-party software.</p>
            <h3>WAIVER AND SEVERABILITY OF TERMS</h3>
            <p>At any time, should Wana Family Network LLC fail to exercise or enforce any right or provision of the Terms, such failure shall not constitute a waiver of such right or provision. If any provision of these Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms remain in full force and effect.</p>
            <h3>CONTACT</h3>
            <p>If you have any questions or concerns regarding these Terms, or to report any and all violations of these Terms, please contact us at:</p>
            <p>Wana Family Network LLC<br />
            3371 Glendale Blvd. #142<br />
            Los Angeles, California 90039</p>
            <p>(747) 231-0567<br /><a href="mailto:help@wanafam.ly">help@wanafam.ly</a></p>

          </div>
        </section>

        <Footer />
      </div>
    );
  }
};

export default Terms;
